services:
  backend:
    image: backend
    volumes:
      - backend-data:/etc/data
    build: .
    ports:
      - "80:80"
  db:
    ports:
      - "5432:5432"
    image: "postgres"
    volumes:
      - db-data:/etc/data
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  db-data:
  backend-data:
