services:
  backend:
    image: backend
    volumes:
      - data:/etc/data
    build: .
    ports:
      - "80:80"
    environment:
      DB_HOST: postgres
  db:
    hostname: postgres
    image: "postgres"
    volumes:
      - data:/etc/data
    ports:
      - "5432:5432"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  data:
