name: PDM action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    name: build and push to github packages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/openagri-eu/pest-and-disease-management:latest
        docker push ghcr.io/openagri-eu/pest-and-disease-management:latest
